### ISSUE TITLE
Creation of test scripts 

### ISSUE THREAD

**Issue by initd1** [initd1/HackAlert#16]
There is no current test framework available for the project. 

Intent to is develop tests using pytest for each module: 
- Common
- Email
- IP
- main.py 

New issues may be created for tests made for each module.

**Comment by initd1** [comment]
Expected structure for test framework:
````
├── Common
│   ├── __init__.py
│   ├── breach_checker.py
│   ├── config.py
│   └── utils.py
├── Email
│   ├── __init__.py
│   └── email_reputation_checker.py
├── tests
│   ├── Common
│   │   ├── __init__.py
│   │   ├── test_breach_checker.py
│   │   ├── test_config.py
│   │   └── test_utils.py
│   ├── Email
│   │   ├── __init__.py
│   │   └── test_email_reputation_checker.py
│   └── test_config.py
├── config.ini
├── main.py
└── README.md
````

Require a tests directory, with a test file for each module (email, IP, Common etc) with the corresponding file as shown above.

**Comment by GH-Syn** [comment]
## Issue Regarding Testing
 > **Warning** Integration testing and (some) unit tests can't be done if they require an api key. This must be done off the books unfortunately.

**Comment by initd1** [comment]
> * Integration tests can't be done if they require an API key ☹️
> * What I can suggest is creating an actions workflow and listing any keys as repository secrets. I would be careful with this though, as there is a set amount of times that keys can be used (dependent on subscription type)

that is correct. The VirusTotal API Key has a limit of 4 requests per minute if it's a free API Key
and HIBP API has a 10 requests per minute limit for the basic one.

**Comment by initd1** [comment]
@GH-Syn Please update README.md with instructions on how to set up the test and execute tests.
