### ISSUE TITLE
debug support with `logging.py` module

### ISSUE THREAD

**Issue by GH-Syn** [initd1/HackAlert#21]
## About
This feature/enhancement implements changes in the header docstring:
https://github.com/initd1/Cyber-Breach-Detector/blob/f848c272f120feff607256c9f5e95fc6b3667f03/Common/utils.py#L1-L5
 - [x] Add an exception in `.gitignore` that disallows logs from being included in commits
 - [x] Move methods that can be converted to functions in `ip_reputation_checker.py`
 - [x] Fix up comments, adding comments where needed and omitting redundant ones. Somewhat pertains to #6

**Comment by initd1** [comment]
Prefer to have the logging changes and the test changes as separate if possible, so the merges can be done separately per issue. 

But not too fussy about it for now.

**Comment by GH-Syn** [comment]
> Prefer to have the logging changes and the test changes as separate if possible, so the merges can be done separately per issue.
> 
> But not too fussy about it for now.

 - I 100% agree. Apologies for not making the PR's separate. To make the best of the situation, if you can make a separate branch for #21 that extrudes from the current [Cyber-Breach-Detector/main](https://github.com/initd1/Cyber-Breach-Detector) branch that would be awesome.

 - Also I wanted to let you know that I really like your idea of naming the project Hack-Alert. It has a great ring to it! Would you be open to changing the repository name to match the new project name?

**Comment by initd1** [comment]
> * I 100% agree. Apologies for not making the PR's separate. To make the best of the situation, if you can make a separate branch for [debug support with `logging.py` module #21](https://github.com/initd1/Cyber-Breach-Detector/issues/21) that extrudes from the current [Cyber-Breach-Detector/main](https://github.com/initd1/Cyber-Breach-Detector) branch that would be awesome. I'll separate the changes that I've made in [add unit tests and additional necessary omissions #20](https://github.com/initd1/Cyber-Breach-Detector/pull/20) into the new branch.

Please refer to: https://github.com/initd1/Cyber-Breach-Detector/issues/23
The new branch created from main has been linked

> * I also updated the original issue to match the format of the template that you committed in [3bcb77a](https://github.com/initd1/Cyber-Breach-Detector/commit/3bcb77a6289128054565827be84995ab2b8b5963)

Thanks. Appreciate it.

> * On a separate note, I wanted to let you know that I really like your idea of naming the project Hack-Alert. It has a great ring to it! Would you be open to changing the repository name to match the new project name?

Yes! I was intending to do that. Question: Would the repository rename retain the commit history and branches etc?

**Comment by GH-Syn** [comment]
> Yes! I was intending to do that. Question: Would the repository rename retain the commit history and branches etc?

Git should automatically do that for you, but you'll get a warning saying that the repo name has changed, and it advises you to change that. I believe you can just change the remote url
with `git remote --set-url <new url>`

**Comment by initd1** [comment]
> > Yes! I was intending to do that. Question: Would the repository rename retain the commit history and branches etc?
> 
> * Git should automatically manage everything for you, but you'll get a warning saying that the repo name has changed, and it advises you to change that. I believe you can just change the remote url with `git remote --set-url <new url>`.
> * As for retaining the commit history and branches, yes.

thank you. I have renamed the repo to HackAlert.  I do intend to rename main.py to hackalert.py, which I will create a new issue for. 

Also invited you as a Collaborator. Appreciate your contribution to this repo :)

**Comment by GH-Syn** [comment]
Thank you, and I appreciate this honor you've given me. it's been a blast working on this with you.

**Comment by GH-Syn** [comment]
- Closed as of #25
