### ISSUE TITLE
Integration of logging module

### ISSUE THREAD

**Issue by initd1** [initd1/HackAlert#23]
**Is your feature request related to a problem? Please describe.**
Currently, there is no logging module integrated in the code

**Describe the solution you'd like**
A logging module with different logging levels for INFO, DEBUG and FATAL

**Comment by GH-Syn** [comment]
Should the log also write to log files? If so, how do you want this done. One way is to have a file named <date-info>.log. Another way is to have different files pertaining to their log level. For example, having debug.log, error.log, critical.log all as separate files.

**Comment by GH-Syn** [comment]
Also can I please have contribution perms to edit issues
