### ISSUE TITLE
Logger module does not write to `traceback.log` file

### ISSUE THREAD

**Issue by initd1** [initd1/HackAlert#43]
**Describe the bug**
The logger module does not write any logs to `Logs/traceback.log`.

**To Reproduce**
1. Run script with any of the valid options for example `python hackalert.py -e k@k.cm`
2. Terminal output is displayed with the results of the breach data
3. No logs of any Logger level is written to the log file

**Expected behavior**
Logs of all Log levels [INFO,DEBUG etc.] must be written to the log file configured in `Config/logger.ini` file

**Device Details (please complete the following information):**
 - Device: MacBook
 - OS: macOS 13.3
 - Python Version: 3.9.13

**Device Details (please complete the following information):**
 - Device: Desktop PC
 - OS: Windows 10 
 - Python Version: 3.9.13

**Comment by GH-Syn** [comment]
Note that I'm on a linux machine so when I fix this it would be great if you could also test it to make sure that it works on windows.

**Comment by GH-Syn** [comment]
Legend.
