### ISSUE TITLE
config file not found.

### ISSUE THREAD

**Issue by Mrpaul32** [initd1/HackAlert#52]
CRITICAL:root:Fatal Error: Config file not found

Don't think I missed any steps. Can't figure this one out.

**Comment by GH-Syn** [comment]
Hmm, that's odd. I'll take a look. Thanks for the report.

**Comment by initd1** [comment]
Hi @Mrpaul32, have you followed this step from the README.md?
https://github.com/initd1/HackAlert#prerequisites

You would need to add the API keys for Virustotal and Have I Been Owned in the config.ini file.

**Comment by initd1** [comment]
@Mrpaul32 did you manage to get it working?

**Comment by Mrpaul32** [comment]
Sorry for the late reply.. deleted everything and started from scratch and so far everything is running as should be.  Problem now is HIBP changed their API so I error out when I run it now with an invalid API /Facepalm
